import React from "react";

// export const metadata = {
//     title: "Course page",
//     description: "Generated by create next app",
// };

// or Dynamic metadata
export async function generateMetadata({ params }) {
    const name = params.courseid.split('%20').join(' ');
    const CardDetails = await fetch(
        `https://ny-server.vercel.app/choosepath/${name}`
    );
    const data = await CardDetails.json();
    return {
        title: data.heading,
        description: data.shortDetails,
        images: {
            url: data.banner,
            alt: data.banner,
        },
    };
}

async function page({ params }) {
    const name = params.courseid.split('%20').join(' ');
    const CardDetails = await fetch(
        `https://ny-server.vercel.app/choosepath/${name}`
    );
    const data = await CardDetails.json();
    return (
        <div>
            <div className=" space-y-5 my-10 max-w-[1220px] mx-auto">
                <h1 className=" text-5xl">{data.heading}</h1>
                <h1>{data.shortDetails}</h1>
                <img className=" size-[400px]" src={data.banner} alt="" />
            </div>

        </div>
    );
}

export default page;

export async function generateStaticParams() {
    const data = await fetch(`https://ny-server.vercel.app/choosepath`);
    const course = await data.json();
    return course.map((item) => item.productID);
}